#!/usr/bin/env bash
# Apply ePass to a Linux 7.2.y tree: the overlay files, the synced
# epass-core sources (as the built-in Rust crate kernel/bpf/epass/), and
# the patch series. Idempotent: run it again after changing epass-core.
#
#   kernel/apply.sh /path/to/linux-7.2.y
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
core="$here/../core-rs/epass-core"
tree="${1:?usage: $0 <linux tree>}"
tree="$(cd "$tree" && pwd)"

[ -f "$tree/kernel/bpf/verifier.c" ] || { echo "$tree is not a kernel tree" >&2; exit 1; }
version="$(make -s -C "$tree" kernelversion 2>/dev/null || true)"
case "$version" in
  7.2*) ;;
  *) echo "warning: patches target Linux 7.2.y, tree is '$version'" >&2 ;;
esac

# 1. Patches to existing files (skip the ones already applied).
for p in "$here"/patches/*.patch; do
  if (cd "$tree" && git apply --reverse --check "$p" 2>/dev/null); then
    echo "already applied: $(basename "$p")"
  else
    (cd "$tree" && git apply "$p")
    echo "applied: $(basename "$p")"
  fi
done

# 2. New files.
cp -r "$here/overlay/." "$tree/"

# 3. The core: epass-core/src becomes the crate kernel/bpf/epass/epass_core.rs.
dst="$tree/kernel/bpf/epass"
find "$dst" -mindepth 1 -maxdepth 1 ! -name Makefile -exec rm -rf {} +
cp -r "$core/src/." "$dst/"
rm -f "$dst/ir/parse.rs"           # `text` feature: userspace only
cp "$core/include/epass.h" "$dst/epass.h"
spdx='// SPDX-License-Identifier: GPL-2.0-only'
while IFS= read -r -d '' f; do
  { echo "$spdx"; cat "$f"; } > "$f.tmp" && mv "$f.tmp" "$f"
done < <(find "$dst" -name '*.rs' ! -name lib.rs -print0)
{
  echo "$spdx"
  echo "//! GENERATED by the ePass repository's kernel/apply.sh from"
  echo "//! core-rs/epass-core/src/lib.rs. Do not edit; change epass-core instead."
  # Kernel lints the core is not written against (it has its own, stricter,
  # set: no panics, no indexing, no unwrap; see core-rs/epass-core/Cargo.toml).
  echo '#![allow(missing_docs, unreachable_pub, rust_2018_idioms, dead_code)]'
  echo '#![allow(clippy::all, clippy::undocumented_unsafe_blocks, clippy::ptr_as_ptr)]'
  echo '#![allow(clippy::cast_lossless, clippy::as_underscore, clippy::ref_as_ptr)]'
  echo '#![allow(clippy::ptr_cast_constness, clippy::as_ptr_cast_mut)]'
  grep -v '^#!\[no_std\]$' "$dst/lib.rs"   # kbuild adds no_std itself
} > "$dst/epass_core.rs"
rm "$dst/lib.rs"
echo "synced epass-core ($(git -C "$here/.." rev-parse --short HEAD 2>/dev/null || echo '?')) into kernel/bpf/epass/"

cat <<MSG
done. Configure with:
  scripts/kconfig/merge_config.sh -m .config $here/config/epass.config && make LLVM=1 olddefconfig
MSG
