name: Build ePass

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  rust-core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            libbpf-dev \
            libelf-dev \
            pkg-config \
            zlib1g-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build core-rs
        run: cargo build --release --workspace
        working-directory: core-rs

      - name: Test core-rs
        run: cargo test --release --workspace
        working-directory: core-rs
