name: Build and Testing ePass

on:
  push:
    branches: [ "main", "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependency
      run: sudo apt-get install -y libbpf-dev

    - name: Configure CMake
      run: cmake -S core -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Install
      run: sudo cmake --install build --config Release

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: |
        ./gen_tests.sh
        ./run_tests.sh

